version: '3'
services:
    application:
        build: code
        volumes:
            # Symlink or setup Laravel/Lumen on ./app directory.
            - ./app:/var/www/laravel
            - ./logs/laravel:/var/www/laravel/storage/logs
        tty: true
    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: laravel
            TEST_DB_NAME: laravel_test
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        depends_on: 
            - application
    redis:
        image: redis:alpine
    php:
        build: php7-fpm
        environment:
            MAIL_ENCRYPTION: 0
            MAIL_PRETEND: 0
            MAIL_USERNAME: null
            MAIL_PASSWORD: null
        volumes_from:
            - application
        depends_on: 
            - application
            - db
            - redis
        links:
            - db
            - redis
    nginx:
        build: nginx
        links:
            - php
        volumes_from:
            - application
        volumes:
            - ./logs/nginx/:/var/log/nginx
        depends_on: 
            - db
            - php
            - redis
            - mailcatcher
        ports:
            - 80:80
    elk:
        image: willdurand/elk
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - application
            - php
            - nginx
        ports:
            - 81:80
    mailcatcher:
        build: mailcatcher
        ports:
            - 82:1080
            - 25:1025
